name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

  build-2:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'      # See 'Options' for more details
          distribution: 'graalvm' # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}
          #set-java-home: 'true'
          native-image-musl: 'true'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build executable with statically linked libs
        run: ./gradlew nativeCompile --build-args="--static" --build-args="--libc=musl"

  build-3:
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '24'      # See 'Options' for more details
          distribution: 'graalvm' # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}
          set-java-home: 'true'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build windows executable with half-statically linked libs
        run: ./gradlew nativeCompile --build-args="--static-nolibc" --build-args="-H:+ForeignAPISupport"
