name: Commit jars

on:
  workflow_dispatch:
  push:
    tags:
      - 'release-**'

jobs:
  build-1:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle Wrapper
        run: ./gradlew jar
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/libs/*.jar
          file_glob: true
          body: "Read the readme file for details."

  build-2:
    needs: build-1
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' for more details
          distribution: 'graalvm' # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}
          set-java-home: 'true'
          native-image-musl: 'true'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build executable with statically linked libs
        run: ./gradlew nativeCompile --build-args="--static"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/native/nativeCompile/*
          file_glob: true
          body: "Read the readme file for details."

  build-3:
    needs: build-2
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'      # See 'Options' for more details
          distribution: 'graalvm' # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}
          set-java-home: 'true'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build windows executable with half-statically linked libs
        run: ./gradlew nativeCompile --build-args="--static-nolibc" --build-args="-H:+ForeignAPISupport"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/native/nativeCompile/*
          file_glob: true
          body: "Read the readme file for details."
